### PR TITLE
Rotate xaxis in graph and align perf results as table

### PR DESCRIPTION
**Pull request by aravindavk**
Aligned results looks like this now,

```
==== Comparision from Tag: v5.0 to 2019-02-22 ====

create            1050.184420 ->   1121.324604    6.774066%
delete            2020.406500 ->   2519.378406   24.696610%
append            1166.633000 ->   1273.064184    9.122936%
overwrite         1246.115500 ->   1342.000157    7.694685%
rename             402.971800 ->    490.174182   21.639822%
mkdir             1056.783300 ->   1151.591566    8.971401%
rmdir             1554.033200 ->   2129.735948   37.045717%
symlink           2248.501000 ->   2851.497286   26.817701%
setxattr          2665.931900 ->   3607.386772   35.314288%
chmod             2115.130800 ->   2560.010820   21.033216%
delete-renamed    2075.904900 ->   2636.512033   27.005434%
read              2198.269300 ->   3254.721230   48.058349%
readdir           6106.614000 ->   6095.616121   -0.180098%
stat              2999.813700 ->   3802.392369   26.754284%
getxattr          6575.097500 ->   6656.370460    1.236072%
ls-l              2758.303400 ->   5999.937487  117.522753%
==== End of results ====
```

Signed-off-by: Aravinda VK <avishwan@redhat.com>

### CODE REVIEW

**Comment by aravindavk** [comment]
Rotated xaxis labels preview:

v5 0-create

v5 0-read

**Comment by aravindavk** [comment]
@sac-urs @amarts ^^

**Comment by amarts** [comment]
Awesome! Looks really cool!

**Comment by sac-urs** [comment]
Very nice, beautiful.

**Pull request merged**
